<div style="
    background: #FADADD;
    color: #6D517A;
    padding: 12px;
    border-radius: 10px;
    text-align: center;
    font-size: 24px;
    font-weight: bold;
    border: 2px solid #E8C7D1;">
    
    🌐 Website Name : Old Reddit Archive 🌐
    
</div>

<div style="
    background: #FADADD;
    color: #6D517A;
    padding: 12px;
    border-radius: 10px;
    text-align: center;
    font-size: 24px;
    font-weight: bold;
    border: 2px solid #E8C7D1;">
    
    🌐 Step 1 : Sending HTTP Request 🌐
    
</div>

In [3]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [4]:
url = "https://old.reddit.com/"
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/137.0 Safari/537.36"
}

response = requests.get(url, headers=headers)

print("Status Code:", response.status_code)

Status Code: 200

<div style="
    background: #FADADD;
    color: #6D597A;
    padding: 12px;
    border-radius: 10px;
    text-align: center;
    font-size: 24px;
    font-weight: bold;
    border: 2px solid #E8C7D1;">
    
    🌐 Step 2 : Extracting and parsing  html content 🌐
    
</div>

In [5]:
soup = BeautifulSoup(response.text,"html.parser" )

<div style="
    background: #FADADD;
    color: #6D597A;
    padding: 12px;
    border-radius: 10px;
    text-align: center;
    font-size: 24px;
    font-weight: bold;
    border: 2px solid #E8C7D1;">
    
    🌐 Step 3 : Extracting Data 🌐
    
</div>

In [6]:
posts = soup.find_all("div", class_="thing")

print("Total Posts Found:", len(posts))

Total Posts Found: 25

In [7]:
titles = []
authors = []
subreddits = []
upvotes = []
comments = []
links = []
post_ids = []

for post in posts:

    # Title
    title = post.find("a", class_="title")
    if title:
        titles.append(title.get_text(strip=True))
        links.append(title.get("href"))
    else:
        titles.append("N/A")
        links.append("N/A")

    # Author
    author = post.get("data-author")
    authors.append(author if author else "N/A")

    # Subreddit
    subreddit = post.get("data-subreddit")
    subreddits.append(subreddit if subreddit else "N/A")

    # Post ID
    post_ids.append(post.get("data-fullname"))

    # Upvotes
    score = post.find("div", class_="score unvoted")

    if score:
        value = score.get("title")
        if value:
            upvotes.append(value)
        else:
            upvotes.append(score.text.strip())
    else:
        upvotes.append("N/A")

    # Comments
    comment_tag = post.find("a", string=lambda x: x and "comment" in x.lower())

    if comment_tag:
        comments.append(comment_tag.text.strip())
    else:
        comments.append("N/A")

In [8]:
reddit_df = pd.DataFrame({
    "Post ID": post_ids,
    "Title": titles,
    "Author": authors,
    "Subreddit": subreddits,
    "Upvotes": upvotes,
    "Comments": comments,
    "Post Link": links
})

reddit_df

,Post ID,Title,Author,Subreddit,Upvotes,Comments,Post Link
0,t3_1ukbka5,latest claims,NoticeSafe7790,indianbikes,2052,263 comments,https://i.redd.it/uvb3wjedqjah1.jpeg
1,t3_1ukdc06,Ladies & Ladies- Toxic (Hindi) | Yash | Nayant...,Deepakhn,BollyBlindsNGossip,68,253 comments,https://m.youtube.com/watch?v=wya96yCsZZY
2,t3_1uk913s,The slaps in the end😭🙏🏼,One-Blood-8639,MechanicalPandey,3949,138 comments,https://v.redd.it/uqittba14jah1
3,t3_1uk9epj,A Towel Isn't Optional—It's Basic Hygiene 🤸,Username_kya_rakhu,Fitness_India,2482,223 comments,https://i.redd.it/j3du1u0c7jah1.jpeg
4,t3_1uk8vd7,Throwback to Sonam looking pissed as Salman wi...,mx-shot,BollyBlindsNGossip,1322,124 comments,https://v.redd.it/e2acx2hd2jah1
5,t3_1uka63q,India has around 229 billionaires according to...,TheEndOfCircle11,IndianFocus,3094,133 comments,https://i.redd.it/q11oof4vdjah1.jpeg
6,t3_1ukdtx4,Isn't it Funny we all Know Ethanol is Scam but...,Icy_Software4065,IndianFocus,1177,158 comments,https://i.redd.it/e44kafy0ckah1.jpeg
7,t3_1ukdxrt,a clay sculpture i am currently making...,vidhikaroy,indiasocial,1338,250 comments,https://www.reddit.com/gallery/1ukdxrt
8,t3_1ukdcer,Ladies & Ladies- Toxic (Telugu) | Yash | Nayan...,No_Quantity5477,tollywood,77,106 comments,https://youtu.be/n8sMfqOO9c0?si=rR7MOGAgnmYo0HwU
9,t3_1ukfeht,This is why I don’t bring any of my female bes...,Radiant_Belt_4467,TwentiesIndia,•,153 comments,https://i.redd.it/qbahis36skah1.jpeg
10,t3_1ukcrdr,Graphic artist Matt Taylor says that VCARB doe...,austinbucco,formula1,3464,469 comments,https://i.redd.it/d8815acg1kah1.jpeg
11,t3_1uk8tpb,For the love of Arizona,Dev1412,SipsTea,8858,857 comments,https://i.redd.it/0i2i7gv92jah1.jpeg
12,t3_1ukb6rg,Love how she’s so confident in her daily vlogs...,Finenthu,InstaCelebsGossip,220,259 comments,https://v.redd.it/th6bqd7nmjah1
13,t3_1ukc0rn,Sunita discusses about being cheated by Govind...,Margarita_pizza001,InstaCelebsGossip,427,101 comments,https://v.redd.it/xza3ttdjujah1
14,t3_1ukcb3j,He finally embraced his new role as Supreme Le...,Impossible-Box717,soccercirclejerk,5294,76 comments,https://i.redd.it/a8l3id66xjah1.jpeg
15,t3_1ukeu8q,Hyderabad Police used drones to catch people d...,itsmukeshrishi,hyderabad,409,34 comments,https://v.redd.it/0730j8kwlkah1
16,t3_1ukeo05,Jay Shree Ram 🙏,RRR1557,IndiaMemes,660,77 comments,https://i.redd.it/kr0ec6kgkkah1.jpeg
17,t3_1ukdyhh,a clay sculpture i am currently making...,vidhikaroy,Indian_flex,806,93 comments,https://www.reddit.com/gallery/1ukdyhh
18,t3_1uk1asb,What was that day,Ambitious_Voice_9310,indiasocial,1807,672 comments,https://i.redd.it/n5if3v5rghah1.jpeg
19,t3_1ukfh5v,Yash's Warning. I Don't Think even Indian Pare...,Mental-Dinner-6827,BollyBlindsNGossip,•,86 comments,https://i.redd.it/mrkn6uczskah1.jpeg
20,t3_1ukbjv6,A person who thinks all the time,Forward_Buffalo_4389,funnyIndia,973,79 comments,https://i.redd.it/yo6nx5t9qjah1.jpeg
21,t3_1ukc1to,Ggs to my cat,DatabaseAvailable501,memes,9257,72 comments,https://i.redd.it/q31iikutujah1.jpeg
22,t3_1ukbmu9,Sufi Motiwala faces homophobic comments by Har...,Finenthu,InstaCelebsGossip,399,Sufi Motiwala faces homophobic comments by Har...,https://v.redd.it/b547zhzhpjah1
23,t3_1ukb15o,UPSC teacher Amit Kilhor is shamelessly defend...,God_Emperor__Doom,youtubeindia,891,185 comments,https://v.redd.it/inr10s4gljah1
24,t3_1ukbesn,Nayara cuts fuel prices. Will OMCs follow?,semanticweb,CarsIndia,430,51 comments,https://i.redd.it/8m0m4ujuojah1.png

In [9]:
reddit_df.head(10)

,Post ID,Title,Author,Subreddit,Upvotes,Comments,Post Link
0,t3_1ukbka5,latest claims,NoticeSafe7790,indianbikes,2052,263 comments,https://i.redd.it/uvb3wjedqjah1.jpeg
1,t3_1ukdc06,Ladies & Ladies- Toxic (Hindi) | Yash | Nayant...,Deepakhn,BollyBlindsNGossip,68,253 comments,https://m.youtube.com/watch?v=wya96yCsZZY
2,t3_1uk913s,The slaps in the end😭🙏🏼,One-Blood-8639,MechanicalPandey,3949,138 comments,https://v.redd.it/uqittba14jah1
3,t3_1uk9epj,A Towel Isn't Optional—It's Basic Hygiene 🤸,Username_kya_rakhu,Fitness_India,2482,223 comments,https://i.redd.it/j3du1u0c7jah1.jpeg
4,t3_1uk8vd7,Throwback to Sonam looking pissed as Salman wi...,mx-shot,BollyBlindsNGossip,1322,124 comments,https://v.redd.it/e2acx2hd2jah1
5,t3_1uka63q,India has around 229 billionaires according to...,TheEndOfCircle11,IndianFocus,3094,133 comments,https://i.redd.it/q11oof4vdjah1.jpeg
6,t3_1ukdtx4,Isn't it Funny we all Know Ethanol is Scam but...,Icy_Software4065,IndianFocus,1177,158 comments,https://i.redd.it/e44kafy0ckah1.jpeg
7,t3_1ukdxrt,a clay sculpture i am currently making...,vidhikaroy,indiasocial,1338,250 comments,https://www.reddit.com/gallery/1ukdxrt
8,t3_1ukdcer,Ladies & Ladies- Toxic (Telugu) | Yash | Nayan...,No_Quantity5477,tollywood,77,106 comments,https://youtu.be/n8sMfqOO9c0?si=rR7MOGAgnmYo0HwU
9,t3_1ukfeht,This is why I don’t bring any of my female bes...,Radiant_Belt_4467,TwentiesIndia,•,153 comments,https://i.redd.it/qbahis36skah1.jpeg

In [10]:
print("Total Posts:", len(reddit_df))

print("\nUnique Authors:", reddit_df["Author"].nunique())

print("\nUnique Subreddits:", reddit_df["Subreddit"].nunique())

Total Posts: 25

Unique Authors: 23

Unique Subreddits: 19

In [11]:
keyword = "Python"

filtered = reddit_df[
    reddit_df["Title"].str.contains(keyword, case=False, na=False)
]

filtered

Empty DataFrame
Columns: [Post ID, Title, Author, Subreddit, Upvotes, Comments, Post Link]
Index: []

<div style="
    background: #FADADD;
    color: #6D597A;
    padding: 12px;
    border-radius: 10px;
    text-align: center;
    font-size: 24px;
    font-weight: bold;
    border: 2px solid #E8C7D1;">
    
    🌐 Step 4 : Storing Data 🌐
    
</div>

In [12]:
reddit_df.to_csv("old_reddit_posts.csv", index=False)

print("CSV Saved Successfully!")

CSV Saved Successfully!

In [13]:
reddit_df.sample(5)

,Post ID,Title,Author,Subreddit,Upvotes,Comments,Post Link
21,t3_1ukc1to,Ggs to my cat,DatabaseAvailable501,memes,9257,72 comments,https://i.redd.it/q31iikutujah1.jpeg
9,t3_1ukfeht,This is why I don’t bring any of my female bes...,Radiant_Belt_4467,TwentiesIndia,•,153 comments,https://i.redd.it/qbahis36skah1.jpeg
18,t3_1uk1asb,What was that day,Ambitious_Voice_9310,indiasocial,1807,672 comments,https://i.redd.it/n5if3v5rghah1.jpeg
6,t3_1ukdtx4,Isn't it Funny we all Know Ethanol is Scam but...,Icy_Software4065,IndianFocus,1177,158 comments,https://i.redd.it/e44kafy0ckah1.jpeg
12,t3_1ukb6rg,Love how she’s so confident in her daily vlogs...,Finenthu,InstaCelebsGossip,220,259 comments,https://v.redd.it/th6bqd7nmjah1

<style>
@keyframes gradient {
    0% {background-position:0% 50%;}
    50% {background-position:100% 50%;}
    100% {background-position:0% 50%;}
}
</style>

<div style="
background:linear-gradient(-45deg,#4F46E5,#06B6D4,#10B981,#F59E0B);
background-size:300% 300%;
animation:gradient 8s ease infinite;
padding:20px;
border-radius:20px;
text-align:center;
color:white;
font-size:30px;
font-weight:bold;
box-shadow:0 10px 30px rgba(0,0,0,0.3);">

🚀 THANK YOU 🚀

<div style="font-size:16px;margin-top:10px;">
Keep Learning • Keep Building • Keep Growing
</div>

</div>